name: Build LLVM Project

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install required tools
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential binutils wget unzip ninja-build

    - name: Download LLVM Project source
      run: |
        wget https://github.com/llvm/llvm-project/releases/download/llvmorg-18.1.8/llvm-project-18.1.8.src.tar.xz
        tar -xJf llvm-project-18.1.8.src.tar.xz

    - name: Build LLVM Project
      run: |
        cd llvm-project-18.1.8.src/llvm
        mkdir build && cd build
        cmake -G Ninja -DLLVM_TARGETS_TO_BUILD=all -DCMAKE_BUILD_TYPE=Release ..
        ninja -j16

    - name: Package output directory
      run: |
        cd llvm-project-18.1.8.src/build
        tar -cJf llvm-output.tar.xz .

    - name: Upload output archive
      uses: actions/upload-artifact@v3
      with:
        name: llvm-output
        path: llvm-project-18.1.8.src/build/llvm-output.tar.xz
