name: Build GNU Make for Android

on:
   workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Android NDK
      run: |
        wget https://dl.google.com/android/repository/android-ndk-r27c-linux.zip
        unzip android-ndk-r27c-linux.zip -d $HOME
        echo "NDK_HOME=$HOME/android-ndk-r27c" >> $GITHUB_ENV

    - name: Download GNU Make source
      run: |
        wget https://ftp.gnu.org/gnu/make/make-4.3.tar.gz
        tar -xzf make-4.3.tar.gz

    - name: Build GNU Make
      run: |
        export NDK_HOME=$HOME/android-ndk-r27c
        export TOOLCHAIN=$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64
        export TARGET_ARCH=arm64-v8a
        export SYSROOT=$TOOLCHAIN/sysroot
        export CC=$TOOLCHAIN/bin/aarch64-linux-android25-clang
        export CXX=$TOOLCHAIN/bin/aarch64-linux-android25-clang++

        cd make-4.3
        ./configure --host=aarch64-linux-android --prefix=$PWD/output
        make
        make install

    - name: Package output directory
      run: |
        cd make-4.3
        tar -cJf output.tar.xz output

    - name: Upload output archive
      uses: actions/upload-artifact@v3
      with:
        name: make-output
        path: make-4.3/output.tar.xz
