name: Build LLVM Toolchain

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v2

      - name: 安装 curl
        run: sudo apt-get install -y curl

      - name: 下载 repo 工具
        run: |
          curl https://storage.googleapis.com/git-repo-downloads/repo > ./repo
          chmod 755 ./repo

      - name: 列出当前目录内容
        run: ls -al  # 添加这一步以调试

      - name: 初始化 LLVM Toolchain
        run: |
          mkdir llvm-toolchain
          cd llvm-toolchain
          ../repo init -u https://android.googlesource.com/platform/manifest -b llvm-toolchain
          cp ../manifest_7714059.xml .repo/manifests  # 确保路径正确
          ../repo init -m manifest_7714059.xml
          ../repo sync -c -j$(($(nproc --all)+1))

      - name: 构建 LLVM Toolchain
        run: |
          cd llvm-toolchain
          python toolchain/llvm_android/build.py --build-name 7714059 --no-build windows --skip stage1
